version: '3.8'

services:
  web:
    build: .
    container_name: snake-game-web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MONGO_URI=mongodb+srv://s26670:3vpHvtdXyLuk1oBE@cluster0.xhxbyrd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: snake-game-db
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: test


volumes:
  mongo-data:
    driver: local
